'use client';
import {useState} from 'react';
import {BookOpen,Footprints,Dumbbell,Users,ArrowRight} from 'lucide-react';
import {activities,activityGroups,Activity} from '@/lib/activities';
const icons=[BookOpen,Footprints,Dumbbell,Users];
export default function ActivityLibrary({onChoose}:{onChoose:(a:{title:string;instructions:string})=>void}){
 const [group,setGroup]=useState(0),[selected,setSelected]=useState<Activity|null>(null),[museum,setMuseum]=useState(''),[company,setCompany]=useState(''),[when,setWhen]=useState('');
 return <section className="activity-library" aria-labelledby="activity-heading"><p className="eyebrow">Idéer till ert lov</p><h2 id="activity-heading">Vad passar ditt barn?</h2><p>Välj ett förslag. Anpassa uppdraget och bestäm belöningen tillsammans.</p><div className="activity-filters" role="group" aria-label="Aktivitetskategori">{activityGroups.map((label,i)=>{const Icon=icons[i];return <button type="button" key={label} aria-pressed={group===i} onClick={()=>{setGroup(i);setSelected(null)}}><Icon size={19}/>{label}</button>})}</div>{group===2&&<p className="activity-note">Deltagande och gemenskap räknas. Anpassa planen när barnet behöver vila – inga förlorade sviter.</p>}<div className="activity-grid">{activities.filter(a=>a.group===group).map(a=><article key={a.id}><span className="eyebrow">{a.duration}</span><h3>{a.title}</h3><p>{a.instructions}</p><button type="button" className="btn light" onClick={()=>{if(a.museum){setSelected(a);setMuseum('');setCompany('');setWhen('')}else onChoose(a)}}>{a.museum?'Välj museum':'Anpassa uppdrag'}<ArrowRight size={16}/></button></article>)}</div>{selected&&<form className="museum-plan" onSubmit={e=>{e.preventDefault();onChoose({title:selected.title,instructions:`Besök ${museum.trim()} tillsammans med ${company.trim()}.${when.trim()?` När: ${when.trim()}.`:''} ${selected.instructions}`})}}><h3>Vilket museum ska barnet besöka?</h3><label htmlFor="museum-name">Museets namn och ort</label><input autoFocus id="museum-name" maxLength={70} required value={museum} onChange={e=>setMuseum(e.target.value)} placeholder="Skriv museet ni har valt"/><label htmlFor="museum-company">Med vem?</label><input id="museum-company" maxLength={60} required value={company} onChange={e=>setCompany(e.target.value)} placeholder="Till exempel en vuxen eller lovgruppen"/><label htmlFor="museum-when">Dag eller tid (valfritt)</label><input id="museum-when" maxLength={50} value={when} onChange={e=>setWhen(e.target.value)} placeholder="Till exempel tisdag efter lunch"/><p>Kontrollera öppettider, åldersregler och eventuell biljett med museet. Ingen bokning eller biljett ingår. Barnet behöver inte skicka bild eller position.</p><button className="btn">Välj belöning och förhandsgranska</button><button type="button" className="btn ghost" onClick={()=>setSelected(null)}>Avbryt</button></form>}</section>
}
