'use client';
import {useState,useEffect,useRef} from 'react';
import {Sun,Leaf,BookOpen,Volleyball,Gift,Check,Mail,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ViewSwitcher from './view-switcher';
import {requestKey,taskInfo,stages,demoData} from '@/lib/experience';
const avatars:any={sun:Sun,leaf:Leaf,book:BookOpen,ball:Volleyball};
export function ProductImage({image,alt}:{image:string,alt:string}){return image?<img className="product-photo" src={'/rewards/'+image+'.png'} alt={alt} width="320" height="240"/>:<Gift className="family-gift" size={66} aria-hidden/>}
export default function ChildExperience({demo=false}:{demo?:boolean}){
 const [data,setData]=useState<any>(demo?demoData():null),[tab,setTab]=useState('today'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(''),[current,setCurrent]=useState<any>(null),[idea,setIdea]=useState(''),[opened,setOpened]=useState(false),[animating,setAnimating]=useState(false),[ready,setReady]=useState(false);const lock=useRef(false),key=useRef('');
 async function refresh(){try{const r=await fetch('/api/state?child=1',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{document.querySelector('link[rel=manifest]')?.setAttribute('href','/child.webmanifest');if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});if(demo){try{const saved=sessionStorage.getItem('hostlovet-child-demo-v2');if(saved)setData(JSON.parse(saved))}catch{}setReady(true);return}const token=location.hash.slice(1);if(token){history.replaceState(null,'','/barn');fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'redeem',token})}).then(r=>r.json()).then((d:any)=>{if(d.error)throw Error(d.error);return refresh()}).catch(e=>setError(e.message))}else refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer)},[demo]);
 useEffect(()=>{if(demo&&ready)sessionStorage.setItem('hostlovet-child-demo-v2',JSON.stringify(data))},[data,ready,demo]);
 async function act(payload:any){if(lock.current)return false;lock.current=true;setBusy(true);setError('');try{if(demo){setData((d:any)=>{if(payload.action==='suggest')return {...d,suggestions:[...d.suggestions,{id:payload.key,title:payload.title,status:'Pending'}]};if(payload.action==='avatar')return {...d,children:[{...d.children[0],avatar:payload.avatar}]};return {...d,challenges:d.challenges.map((a:any)=>a.id===payload.challenge?{...a,...(payload.action==='open_reward'?{opened:1}:{status:({select:'Selected',start:'Started',claim:'Claimed',demo_approve:'Approved',demo_issue:'Issuing',demo_deliver:'Delivered',demo_fail:'Failed'} as any)[payload.action]||a.status})}:a)}})}else{const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),v:any=await r.json();if(!r.ok)throw Error(v.error);await refresh()}return true}catch(e){setError((e as Error).message);return false}finally{lock.current=false;setBusy(false)}}
 const tasks=data?.challenges||[],active=tasks.find((a:any)=>['Started','Selected','Rejected'].includes(a.status))||tasks.find((a:any)=>a.status==='Assigned')||tasks.find((a:any)=>a.status!=='Delivered'),done=tasks.filter((a:any)=>['Approved','Issuing','Delivered'].includes(a.status)),available=tasks.filter((a:any)=>a.status==='Delivered'),next=tasks.find((a:any)=>a.status!=='Delivered'),Avatar=avatars[data?.children?.[0]?.avatar]||Sun;
 function choose(a:any){setCurrent(a);setModal('task')}
 function primary(a:any){if(a.status==='Assigned')return <button className="btn" disabled={busy} onClick={()=>act({action:'select',challenge:a.id})}>Välj uppdrag <ArrowRight size={18}/></button>;if(['Selected','Rejected'].includes(a.status))return <button className="btn" disabled={busy} onClick={()=>act({action:'start',challenge:a.id})}>Starta <ArrowRight size={18}/></button>;if(a.status==='Started')return <button className="btn" disabled={busy} onClick={()=>{setCurrent(a);setModal('confirm')}}>Jag är klar <Check size={18}/></button>;return <p className="child-status" role="status">{a.status==='Claimed'?'Din vuxen får godkänna. Du kan välja ett annat uppdrag under tiden.':a.status==='Failed'||a.status==='ManualReview'?'Det tar lite längre tid. Din vuxen hjälper till – du behöver inte göra om uppdraget.':a.status==='Approved'&&taskInfo(a).kind==='family'?'Din vuxen ordnar din familjebelöning.':'Din belöning är på väg. Du har gjort din del!'}</p>}
 const focused=current?tasks.find((a:any)=>a.id===current.id)||current:null,info=focused?taskInfo(focused):null;
 return <><a className="skip" href="#main">Hoppa till innehållet</a><div className="child-brand"><a href={demo?'/barn/demo':'/barn'} className="brand">höstlovet.se</a><span className="role-label child-role">{demo?'Barnvy · demo':'Barnvy'}</span></div>{demo&&<><ViewSwitcher view="demo"/><div className="demo-ribbon">Exempeldata · inga SMS eller riktiga presentkort.</div></>}<main id="main" className="kid-home">{error&&<div className="notice" role="alert">{error}{!demo&&<button className="btn light" onClick={refresh}>Försök igen</button>}</div>}{!data?<section className="kid-empty"><h1>Ditt höstlov väntar</h1><p>Det här är barnens egen sida. Öppna din personliga inbjudningslänk från din vuxen för att se dina uppdrag.</p><a className="btn" href="/barn/demo">Testa barnvyn</a></section>:<><header className="kid-greeting"><div><p className="eyebrow">Ditt höstlov · Hej {data.children[0]?.nickname}!</p><h1>{tab==='today'?'Vad vill du göra idag?':tab==='holiday'?'Mitt lov':'Mina belöningar'}</h1></div><button className="avatar-picker" aria-label="Välj avatar" onClick={()=>setModal('avatar')}><Avatar size={30}/></button></header>
 {tab==='today'&&<>{active?<section className="daily-mission"><div className="daily-copy"><span className="eyebrow">Ditt nästa äventyr</span><h2>{taskInfo(active).title}</h2><p>{taskInfo(active).instructions}</p><span className="status">{stages[active.status]}</span><p className="agreed-reward"><Gift size={18}/> {taskInfo(active).reward}</p>{primary(active)}</div><div className="daily-product"><ProductImage image={taskInfo(active).image} alt={taskInfo(active).reward}/><span>{taskInfo(active).kind==='family'?'Familjebelöning':'Belöningsexempel · test'}</span></div></section>:<section className="kid-empty"><Leaf size={36}/><h2>{tasks.length?'Du har gjort klart dina uppdrag!':'Här börjar ditt höstlov'}</h2><p>{tasks.length?'Njut av lovet. Dina belöningar finns kvar här.':'Din vuxen lägger snart till uppdrag. Du kan också föreslå en egen idé.'}</p>{tasks.length>0&&<button className="btn" onClick={()=>setTab('rewards')}>Se mina belöningar</button>}</section>}
 {tasks.filter((a:any)=>a.id!==active?.id&&a.status==='Assigned').length>0&&<section className="kid-alternatives"><h2>Vill du hellre göra något annat?</h2><p className="muted">Separata uppdrag i din plan. Du kan göra ett eller flera, i din egen takt.</p><div className="alternative-grid">{tasks.filter((a:any)=>a.id!==active?.id&&a.status==='Assigned').slice(0,3).map((a:any)=><button className="alternative" key={a.id} onClick={()=>choose(a)}><ProductImage image={taskInfo(a).image} alt=""/><strong>{taskInfo(a).title}</strong><span>{taskInfo(a).reward}</span><span className="textlink">Visa uppdrag →</span></button>)}</div></section>}
 <button className="btn light idea-button" onClick={()=>{key.current=requestKey();setModal('suggest')}}>Föreslå eget uppdrag <PlusIcon/></button>{data.suggestions?.map((s:any)=><p className="suggestion-line" key={s.id}>{s.title} · {s.status==='Pending'?'Din vuxen funderar på din idé':s.status==='Accepted'?'Din idé finns nu i din plan':'Prata med din vuxen om en annan idé'}</p>)}
 {next&&<section className="next-reward"><div><span className="eyebrow">Min nästa belöning</span><h2>{taskInfo(next).reward}</h2><p>{['Assigned','Selected','Started','Rejected'].includes(next.status)?'Kvar: gör ”'+taskInfo(next).title+'” och få din vuxens godkännande.':next.status==='Claimed'?'Kvar: din vuxen behöver godkänna uppdraget.':'Kvar: din vuxen eller leveransen gör belöningen tillgänglig.'}</p></div><ProductImage image={taskInfo(next).image} alt=""/></section>}</>}
 {tab==='holiday'&&<section className="holiday-list"><p>{done.length} av {tasks.length} uppdrag godkända. Varje steg räknas.</p>{!tasks.length&&<p>Inga uppdrag ännu. Föreslå något du vill göra under Idag.</p>}{tasks.map((a:any)=><button className="holiday-row" key={a.id} onClick={()=>choose(a)}><span className={'leaf-node '+(done.includes(a)?'done':'')}><Leaf size={22}/></span><span><strong>{taskInfo(a).title}</strong><small>{stages[a.status]}</small></span><ArrowRight size={18}/></button>)}</section>}
 {tab==='rewards'&&<><h2>Tillgängliga</h2>{!available.length&&<p className="kid-empty">När din vuxen har godkänt och belöningen är redo hittar du den här.</p>}<div className="reward-grid">{available.map((a:any)=><button className="reward-tile" key={a.id} onClick={()=>{setCurrent(a);setOpened(!!a.opened);setModal('reward')}}><ProductImage image={taskInfo(a).image} alt={taskInfo(a).reward}/><strong>{taskInfo(a).reward}</strong><span><Mail size={18}/> {a.opened?'Visa belöningen':'Öppna ditt kuvert'}</span></button>)}</div><h2 className="subheading">Kommande</h2>{tasks.filter((a:any)=>a.status!=='Delivered').map((a:any)=><div className="upcoming-row" key={a.id}><span>{taskInfo(a).reward}</span><span>{stages[a.status]}</span></div>)}{!next&&<p>Inga fler belöningar på väg just nu.</p>}<h2 className="subheading">Använda eller utgångna</h2><p className="muted">Inga bekräftade använda eller utgångna belöningar. Att öppna ett kuvert räknas inte som att använda belöningen.</p></>}
 {demo&&<details className="demo-controls"><summary>Demoverktyg</summary><p>Prova statusar utan riktiga utskick.</p>{active&&<div className="actions">{[['demo_approve','Godkänn i demo'],['demo_issue','Visa leverans'],['demo_deliver','Gör tillgänglig'],['demo_fail','Visa leveransfel']].map(([action,label])=><button key={action} className="btn light" onClick={()=>act({action,challenge:active.id})}>{label}</button>)}</div>}<button className="btn light" onClick={()=>setData({...demoData(),challenges:[]})}>Visa nytt barn</button><button className="btn light" onClick={()=>setData(demoData())}>Återställ demo</button></details>}
 <p className="kid-privacy">Din vuxen skapar din profil. Vi följer inte var du är och ber aldrig om bilder. Din vuxen kan ta bort din profil.</p></>}</main><nav className="kid-nav" aria-label="Barnets navigation">{[['today','Idag',Sun],['holiday','Mitt lov',Leaf],['rewards','Belöningar',Gift]].map(([value,label,I]:any)=><button key={value} aria-current={tab===value?'page':undefined} onClick={()=>{setTab(value);window.scrollTo({top:0})}}><I size={22}/>{label}</button>)}</nav>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v)setModal('')}}><DialogContent className="modal"><DialogTitle>{modal==='avatar'?'Din avatar':modal==='suggest'?'Vad är din idé?':modal==='confirm'?'Skicka till din vuxen?':modal==='sent'?'Bra jobbat!':modal==='reward'?'En belöning till dig':info?.title||'Ditt uppdrag'}</DialogTitle><DialogDescription>{modal==='suggest'?'Din vuxen bestämmer om uppdraget och eventuell belöning.':modal==='reward'?'En hälsning från din vuxen.':'Ditt lov, ett steg i taget.'}</DialogDescription>{error&&<p role="alert">{error}</p>}
 {modal==='avatar'&&<div className="actions">{Object.entries(avatars).map(([id,I]:any)=><button className="avatar-picker" aria-label={({sun:'Sol',leaf:'Löv',book:'Bok',ball:'Boll'} as Record<string,string>)[id]} key={id} onClick={async()=>{if(await act({action:'avatar',avatar:id}))setModal('')}}><I/></button>)}</div>}
 {modal==='suggest'&&<form onSubmit={async e=>{e.preventDefault();if(await act({action:'suggest',title:idea,key:key.current})){setIdea('');setModal('');}}}><label htmlFor="idea">Mitt uppdrag</label><textarea id="idea" value={idea} onChange={e=>setIdea(e.target.value)} required minLength={3} maxLength={160}/><button className="btn" disabled={busy}>Skicka min idé</button></form>}
 {modal==='task'&&focused&&<><p>{info?.instructions}</p><p><strong>Belöning:</strong> {info?.reward}</p><p>{stages[focused.status]}</p>{primary(focused)}</>}
 {modal==='confirm'&&focused&&<><p>Har du gjort ”{info?.title}”? Din vuxen får godkänna.</p><button className="btn" disabled={busy} onClick={async()=>{if(await act({action:'claim',challenge:focused.id}))setModal('sent')}}>Ja, jag är klar</button><button className="btn light" onClick={()=>setModal('')}>Fortsätt med uppdraget</button></>}
 {modal==='sent'&&<><Check size={36}/><p>Snyggt! Nu väntar vi på din vuxen.</p><button className="btn" onClick={()=>{setModal('');setTab('holiday');window.scrollTo({top:0})}}>Till mitt lov</button></>}
 {modal==='reward'&&info&&(!opened?<div className={'gift-envelope '+(animating?'opening':'')}><Mail size={90}/><p>Du har fått en hälsning</p><button className="btn" disabled={animating} onClick={()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){setOpened(true);act({action:'open_reward',challenge:focused.id});return}setAnimating(true);setTimeout(()=>{setOpened(true);setAnimating(false);act({action:'open_reward',challenge:focused.id})},650)}}>Öppna kuvertet</button><button className="btn ghost" onClick={()=>{setOpened(true);setAnimating(false);act({action:'open_reward',challenge:focused.id})}}>Hoppa över animationen</button></div>:<div className="opened-gift"><ProductImage image={info.image} alt={info.reward}/><h2>{info.reward}</h2><p className="personal-greeting">{info.greeting}</p><dl><dt>Gäller hos</dt><dd>{info.kind==='family'?'Din familj':'Testmiljön – ingen butikskupong har utfärdats'}</dd><dt>Giltighet</dt><dd>{info.kind==='family'?'Kom överens med din vuxen':'Ingen giltighetstid för inlösen i testläget'}</dd><dt>Så använder du den</dt><dd>{info.kind==='family'?'Prata med din vuxen och planera tillsammans.':'Det här visar upplevelsen. En riktig kupong och verifierade villkor kräver en ansluten leverantör.'}</dd></dl></div>)}
 </DialogContent></Dialog></>;
}
function PlusIcon(){return <span aria-hidden>+</span>}
