import { sql } from 'drizzle-orm';
import { sqliteTable, text, integer, uniqueIndex, check } from 'drizzle-orm/sqlite-core';
export const households=sqliteTable('households',{id:text('id').primaryKey(),owner:text('owner').notNull().unique(),name:text('name').notNull(),created:text('created').notNull()});
export const parents=sqliteTable('parent_users',{id:text('id').primaryKey(),household:text('household').notNull().references(()=>households.id),name:text('name').notNull()});
export const children=sqliteTable('child_profiles',{id:text('id').primaryKey(),household:text('household').notNull().references(()=>households.id),nickname:text('nickname').notNull(),phone:text('phone').notNull(),tokenHash:text('token_hash'),tokenExpires:integer('token_expires'),version:integer('version').notNull().default(0),deleted:integer('deleted').notNull().default(0)});
export const templatesTable=sqliteTable('challenge_templates',{id:text('id').primaryKey(),name:text('name').notNull(),amount:integer('amount').notNull(),category:text('category').notNull()});
export const assigned=sqliteTable('assigned_challenges',{id:text('id').primaryKey(),household:text('household').notNull().references(()=>households.id),child:text('child').notNull().references(()=>children.id),template:text('template').notNull(),amount:integer('amount').notNull(),status:text('status').notNull(),created:text('created').notNull()});
export const claims=sqliteTable('completion_claims',{id:text('id').primaryKey(),challenge:text('challenge').notNull().references(()=>assigned.id),created:text('created').notNull()});
export const approvals=sqliteTable('approvals',{id:text('id').primaryKey(),challenge:text('challenge').notNull().unique().references(()=>assigned.id),parent:text('parent').notNull(),created:text('created').notNull()});
export const payments=sqliteTable('payments',{id:text('id').primaryKey(),household:text('household').notNull().references(()=>households.id),amount:integer('amount').notNull(),method:text('method').notNull(),status:text('status').notNull(),created:text('created').notNull()});
export const ledger=sqliteTable('ledger_transactions',{id:text('id').primaryKey(),household:text('household').notNull().references(()=>households.id),available:integer('available').notNull().default(0),reserved:integer('reserved').notNull().default(0),spent:integer('spent').notNull().default(0),refunded:integer('refunded').notNull().default(0),reason:text('reason').notNull(),created:text('created').notNull()});
export const orders=sqliteTable('reward_orders',{id:text('id').primaryKey(),household:text('household').notNull().references(()=>households.id),challenge:text('challenge').notNull().unique().references(()=>assigned.id),status:text('status').notNull(),attempts:integer('attempts').notNull().default(0),nextAttempt:integer('next_attempt').notNull().default(0),scenario:text('scenario').notNull().default('success'),error:text('error'),created:text('created').notNull()});
export const coupons=sqliteTable('coupons',{id:text('id').primaryKey(),order:text('order_id').notNull().unique().references(()=>orders.id),providerRef:text('provider_ref').notNull(),status:text('status').notNull()});
export const notifications=sqliteTable('notifications',{id:text('id').primaryKey(),household:text('household').notNull(),child:text('child').notNull(),body:text('body').notNull(),created:text('created').notNull()});
export const audits=sqliteTable('audit_events',{id:text('id').primaryKey(),household:text('household').notNull(),actor:text('actor').notNull(),event:text('event').notNull(),reference:text('reference').notNull(),created:text('created').notNull()});
export const sessions=sqliteTable('child_sessions',{hash:text('hash').primaryKey(),child:text('child').notNull(),version:integer('version').notNull(),expires:integer('expires').notNull()});
export const limits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});

export const balanceAccounts=sqliteTable('balance_accounts',{household:text('household').primaryKey().references(()=>households.id),available:integer('available').notNull().default(0),reserved:integer('reserved').notNull().default(0),spent:integer('spent').notNull().default(0),refunded:integer('refunded').notNull().default(0)},t=>[check('nonnegative_money',sql`${t.available} >= 0 AND ${t.reserved} >= 0 AND ${t.spent} >= 0 AND ${t.refunded} >= 0`)]);

export const challengeDetails=sqliteTable('challenge_details',{challenge:text('challenge').primaryKey().references(()=>assigned.id),title:text('title').notNull(),instructions:text('instructions').notNull(),reward:text('reward').notNull(),kind:text('kind').notNull().default('gift'),image:text('image').notNull().default(''),greeting:text('greeting').notNull().default('Bra jobbat! Vi är stolta över dig.'),opened:integer('opened').notNull().default(0)});
export const suggestions=sqliteTable('suggestions',{id:text('id').primaryKey(),household:text('household').notNull(),child:text('child').notNull(),title:text('title').notNull(),status:text('status').notNull().default('Pending'),created:text('created').notNull()});
export const childPreferences=sqliteTable('child_preferences',{child:text('child').primaryKey(),avatar:text('avatar').notNull().default('sun')});
